### ISSUE TITLE
dodder-dht-server项目这个类建议改成这样写

### ISSUE THREAD

**Issue by weargle** [xwlcn/Dodder#15]
![image](https://user-images.githubusercontent.com/26951765/116428975-021e1580-a878-11eb-8f29-218319ac5a80.png)

这个类不这样写打包完我本地跑不起来，我不知道你是怎么跑起来，我改成这样才能跑起来，它们间接互相依赖对方。

**Comment by xwlcn** [comment]
我这边本地以及服务器上都没问题。

**Comment by weargle** [comment]
> 我这边本地以及服务器上都没问题。
你使用Java版本几，我始终Java8无论服务器还是本地。

**Comment by weargle** [comment]
> 我这边本地以及服务器上都没问题。

你使用Java版本几，我使用Java8服务器和本地一样结果跑不起来

**Comment by xwlcn** [comment]
> > 我这边本地以及服务器上都没问题。
> 
> 你使用Java版本几，我使用Java8服务器和本地一样结果跑不起来

最近用的 jdk 11，以前用的 8 好像也没问题。服务器上试了下jdk 1.8没问题。

**Comment by weargle** [comment]
> > > 我这边本地以及服务器上都没问题。
> > 
> > 你使用Java版本几，我使用Java8服务器和本地一样结果跑不起来
> 
> 最近用的 jdk 11，以前用的 8 好像也没问题。服务器上试了下jdk 1.8没问题。

我再试试看
