### ISSUE TITLE
关于各个组件的版本

### ISSUE THREAD

**Issue by songjian0270** [xwlcn/Dodder#2]
能不能列下您那边运行环境版本的呢，我们在本地运行的用的版本要么注册不了服务，要么分词就有问题的呢

**Comment by xwlcn** [comment]
@songjian0270 
已更新：
- Nacos-0.8.0 (http://nacos.io)
- Zookeeper-3.4.12 (http://zookeeper.apache.org/)
- Kafka-2.11-2.1.0 (http://kafka.apache.org/)
- Elasticsearch-6.6.0 (https://www.elastic.co/)
- elasticsearch-analysis-ik-6.6.0 (https://github.com/medcl/elasticsearch-analysis-ik)

**Comment by xwlcn** [comment]
另外需要注意的是`dht-server`需要部署到外网ip服务器才能爬取`info_hash`

**Comment by songjian0270** [comment]
好的，谢谢
