### ISSUE TITLE
Failure to find cc.dodder:dodder-common:pom:1.0-SNAPSHOT in http://maven.nuiton.org/release/ was cached in the local repository, resolution will not be reattempted until the update interval of nuiton has elapsed or updates are forced

### ISSUE THREAD

**Issue by 0xddy** [xwlcn/Dodder#9]
Failure to find cc.dodder:dodder-common:pom:1.0-SNAPSHOT in http://maven.nuiton.org/release/ was cached in the local repository, resolution will not be reattempted until the update interval of nuiton has elapsed or updates are forced

**Comment by xwlcn** [comment]
Next update will fix this issue.
